services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: eusi
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orbital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_USER: eusi
      DB_PASSWORD: secret
      DB_HOST: db
      DB_NAME: orbital
      DB_PORT: 5432
    depends_on:
      - db
volumes:
  pgdata: